// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PND_WEB.Repository;

#nullable disable

namespace PND_WEB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250408090842_Init482025")]
    partial class Init482025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PND_WEB.Models.Agent", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODE");

                    b.Property<string>("AgentAdd")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Agent_add");

                    b.Property<string>("AgentName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Agent_name");

                    b.Property<string>("AgentNamekd")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Agent_namekd");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note");

                    b.HasKey("Code");

                    b.ToTable("AGENT");
                });

            modelBuilder.Entity("PND_WEB.Models.AgentAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note");

                    b.Property<string>("PersonInCharge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Person_in_charge");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Phone_number");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("AGENT_ACTION");
                });

            modelBuilder.Entity("PND_WEB.Models.AppUserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staff_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PND_WEB.Models.BlType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODE");

                    b.Property<string>("BlName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BL_name");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Note");

                    b.HasKey("Code");

                    b.ToTable("BL_TYPE");
                });

            modelBuilder.Entity("PND_WEB.Models.Carrier", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODE");

                    b.Property<string>("CarierAdd")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Carier_add");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Carrier_name");

                    b.Property<string>("CarrierNamekd")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Carrier_namekd");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note");

                    b.HasKey("Code");

                    b.ToTable("CARRIER");
                });

            modelBuilder.Entity("PND_WEB.Models.CarrierAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("LccFee")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LCC_Fee");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Note");

                    b.Property<string>("PersonInCharge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Person_in_charge");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Phone_number");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("CARRIER_ACTION");
                });

            modelBuilder.Entity("PND_WEB.Models.Cport", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CODE");

                    b.Property<string>("PortName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PORT_NAME");

                    b.HasKey("Code");

                    b.ToTable("CPORT");
                });

            modelBuilder.Entity("PND_WEB.Models.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CODE");

                    b.Property<string>("CurrName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Curr_name");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Note");

                    b.HasKey("Code");

                    b.ToTable("CURRENCY");
                });

            modelBuilder.Entity("PND_WEB.Models.Fee", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fee1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FEE");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NOTE");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UNIT");

                    b.HasKey("Code");

                    b.ToTable("FEE");
                });

            modelBuilder.Entity("PND_WEB.Models.GoodsType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("GoodsTypes");
                });

            modelBuilder.Entity("PND_WEB.Models.InvoiceType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("InvoiceTypes");
                });

            modelBuilder.Entity("PND_WEB.Models.Kindofpackage", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CODE");

                    b.Property<string>("PackageName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Package_name");

                    b.Property<string>("PackagesDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Packages_description");

                    b.HasKey("Code");

                    b.ToTable("KINDOFPACKAGES");
                });

            modelBuilder.Entity("PND_WEB.Models.Mode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CODE");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Note");

                    b.HasKey("Code");

                    b.ToTable("MODE");
                });

            modelBuilder.Entity("PND_WEB.Models.Quotation", b =>
                {
                    b.Property<string>("QuotationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commodity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Qdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Qsatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Valid")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuotationId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("PND_WEB.Models.QuotationsCharge", b =>
                {
                    b.Property<int>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargeId"));

                    b.Property<string>("ChargeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("QuotationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChargeId");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationsCharges");
                });

            modelBuilder.Entity("PND_WEB.Models.Sourse", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Sourses");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Buy")
                        .HasColumnType("bit");

                    b.Property<bool?>("Checked")
                        .HasColumnType("bit");

                    b.Property<bool?>("Cont")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DebitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("ExchangeRate")
                        .HasColumnType("real");

                    b.Property<float?>("MVat")
                        .HasColumnType("real");

                    b.Property<bool?>("Sell")
                        .HasColumnType("bit");

                    b.Property<string>("SerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SerPrice")
                        .HasColumnType("real");

                    b.Property<float?>("SerQuantity")
                        .HasColumnType("real");

                    b.Property<string>("SerUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SerVat")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DebitId");

                    b.ToTable("TblCharges");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCnee", b =>
                {
                    b.Property<string>("Cnee")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CNEE");

                    b.Property<string>("Caddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CAddress");

                    b.Property<string>("Ccity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CCity");

                    b.Property<string>("CpersonInCharge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CPerson_in_charge");

                    b.Property<string>("Haddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("HAddress");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TaxID");

                    b.Property<string>("Vaddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("VAddress");

                    b.Property<string>("Vcnee")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("VCNEE");

                    b.HasKey("Cnee");

                    b.ToTable("tbl_CNEE");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCneeAdd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adds")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Adds");

                    b.Property<string>("Cnee")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CNEE");

                    b.Property<string>("PersonInCharge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PersonInCharge");

                    b.Property<string>("Place")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Place");

                    b.HasKey("Id");

                    b.HasIndex("Cnee");

                    b.ToTable("tbl_CNEE_ADD");
                });

            modelBuilder.Entity("PND_WEB.Models.TblConth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Cmb")
                        .HasColumnType("float");

                    b.Property<string>("ContNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ContType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsDepcription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GrossWeight")
                        .HasColumnType("float");

                    b.Property<string>("Hbl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HblNavigationHbl")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SealNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HblNavigationHbl");

                    b.ToTable("TblConths");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCustomer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Customer_ID");

                    b.Property<string>("ComAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Com_Address");

                    b.Property<string>("ComAddresskd")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Com_Addresskd");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Company_Name");

                    b.Property<string>("CompanyNamekd")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Company_Namekd");

                    b.Property<string>("Contact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Contact");

                    b.Property<string>("DutyPerson")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Duty_Person");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Website");

                    b.HasKey("CustomerId");

                    b.ToTable("tbl_CUSTOMER");
                });

            modelBuilder.Entity("PND_WEB.Models.TblHbl", b =>
                {
                    b.Property<string>("Hbl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HBL");

                    b.Property<string>("BlType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BL_type");

                    b.Property<string>("Cnee")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CNEE");

                    b.Property<bool?>("Collect")
                        .HasColumnType("bit")
                        .HasColumnName("Collect");

                    b.Property<string>("ContSealNo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Cont_Seal_No");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Customer_ID");

                    b.Property<string>("CustomsDeclarationNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Customs_declaration_No");

                    b.Property<DateTime?>("DoDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DO_date");

                    b.Property<bool?>("FreightCharge")
                        .HasColumnType("bit")
                        .HasColumnName("Freight_charge");

                    b.Property<string>("FreightPayable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Freight_Payable");

                    b.Property<string>("GoodsDesciption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Goods_desciption");

                    b.Property<double?>("GrossWeight")
                        .HasColumnType("float")
                        .HasColumnName("Gross_weight");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Invoice_No");

                    b.Property<DateTime?>("IssueDateH")
                        .HasColumnType("datetime2")
                        .HasColumnName("Issue_dateH");

                    b.Property<string>("IssuePlaceH")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Issue_placeH");

                    b.Property<string>("MarkNos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Mark_Nos");

                    b.Property<string>("NomFree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nom_Free");

                    b.Property<string>("NotifyParty")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Notify_party");

                    b.Property<string>("NumberofOrigins")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NumberofOrigins");

                    b.Property<DateTime?>("OnBoardDateH")
                        .HasColumnType("datetime2")
                        .HasColumnName("OnBoard_dateH");

                    b.Property<string>("Pic")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PIC");

                    b.Property<string>("PicPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PIC_phone");

                    b.Property<bool?>("Prepaid")
                        .HasColumnType("bit")
                        .HasColumnName("Prepaid");

                    b.Property<string>("Quantity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Quantity");

                    b.Property<string>("RequestId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Request_ID");

                    b.Property<string>("Shipper")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Shipper");

                    b.Property<string>("SiNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SI_No");

                    b.Property<double?>("Tonnage")
                        .HasColumnType("float")
                        .HasColumnName("Tonnage");

                    b.Property<string>("Volume")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Volume");

                    b.HasKey("Hbl");

                    b.HasIndex("Cnee");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RequestId");

                    b.HasIndex("Shipper");

                    b.ToTable("tbl_HBL");
                });

            modelBuilder.Entity("PND_WEB.Models.TblHscode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Aanzfta")
                        .HasColumnType("float");

                    b.Property<double?>("Acfta")
                        .HasColumnType("float");

                    b.Property<double?>("Ahkfta")
                        .HasColumnType("float");

                    b.Property<double?>("Aifta")
                        .HasColumnType("float");

                    b.Property<double?>("Ajcep")
                        .HasColumnType("float");

                    b.Property<double?>("Akfta")
                        .HasColumnType("float");

                    b.Property<double?>("Atiga")
                        .HasColumnType("float");

                    b.Property<string>("ChiTietGiamVat")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Chi_tiet_giam_VAT");

                    b.Property<string>("ChinhSachHangHoa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Chinh_sach_hang_hoa");

                    b.Property<double?>("Cptpp")
                        .HasColumnType("float");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Don_vi_tinh");

                    b.Property<double?>("Evfta")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_chu");

                    b.Property<string>("GhiChuKhongDau")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_chu_khong_dau");

                    b.Property<string>("GiamVat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Giam_VAT");

                    b.Property<string>("HsCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("HS_CODE");

                    b.Property<string>("MoTaHangHoaE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mo_ta_hang_hoaE");

                    b.Property<string>("MoTaHangHoaV")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mo_ta_hang_hoaV");

                    b.Property<string>("MoTaKhongDau")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mo_ta_khong_dau");

                    b.Property<double?>("RceptA")
                        .HasColumnType("float");

                    b.Property<double?>("RceptB")
                        .HasColumnType("float");

                    b.Property<double?>("RceptC")
                        .HasColumnType("float");

                    b.Property<double?>("RceptD")
                        .HasColumnType("float");

                    b.Property<double?>("RceptE")
                        .HasColumnType("float");

                    b.Property<double?>("RceptF")
                        .HasColumnType("float");

                    b.Property<string>("ThueBvmt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Thue_BVMT");

                    b.Property<double?>("ThueNkTt")
                        .HasColumnType("float")
                        .HasColumnName("Thue_NK_TT");

                    b.Property<double?>("ThueNkUd")
                        .HasColumnType("float")
                        .HasColumnName("Thue_NK_UD");

                    b.Property<string>("ThueVat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Thue_VAT");

                    b.Property<double?>("Ttdb")
                        .HasColumnType("float");

                    b.Property<double?>("Ukvfta")
                        .HasColumnType("float");

                    b.Property<double?>("Vcfta")
                        .HasColumnType("float");

                    b.Property<double?>("Vjepa")
                        .HasColumnType("float");

                    b.Property<double?>("Vkfta")
                        .HasColumnType("float");

                    b.Property<double?>("VnEaeu")
                        .HasColumnType("float");

                    b.Property<double?>("VnLao")
                        .HasColumnType("float");

                    b.Property<double?>("Vncu")
                        .HasColumnType("float");

                    b.Property<double?>("Xk")
                        .HasColumnType("float");

                    b.Property<double?>("Xkcptpp")
                        .HasColumnType("float");

                    b.Property<double?>("Xkev")
                        .HasColumnType("float");

                    b.Property<double?>("Xkukv")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_HSCODE");
                });

            modelBuilder.Entity("PND_WEB.Models.TblInvoice", b =>
                {
                    b.Property<string>("DebitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DebitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hbl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HblNavigationHbl")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupplierId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DebitId");

                    b.HasIndex("HblNavigationHbl");

                    b.HasIndex("SupplierId");

                    b.ToTable("TblInvoices");
                });

            modelBuilder.Entity("PND_WEB.Models.TblJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Job_ID");

                    b.Property<string>("Agent")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Agent");

                    b.Property<string>("Carrier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Carrier");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("datetime2")
                        .HasColumnName("ETA");

                    b.Property<DateTime>("Etd")
                        .HasColumnType("datetime2")
                        .HasColumnName("ETD");

                    b.Property<string>("GoodsType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Goods_type");

                    b.Property<DateTime?>("IssueDateM")
                        .HasColumnType("datetime2")
                        .HasColumnName("Issue_dateM");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Job_date");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Link");

                    b.Property<string>("Mbl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MBL");

                    b.Property<string>("Mode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mode");

                    b.Property<DateTime?>("OnBoardDateM")
                        .HasColumnType("datetime2")
                        .HasColumnName("OnBoard_dateM");

                    b.Property<string>("PlaceofDelivery")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PlaceofDelivery");

                    b.Property<string>("PlaceofReceipt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PlaceofReceipt");

                    b.Property<string>("Pod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("POD");

                    b.Property<string>("Podel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PODel");

                    b.Property<string>("Podis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PODis");

                    b.Property<string>("Pol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("POL");

                    b.Property<string>("PreCariageBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pre_Cariage_by");

                    b.Property<int?>("UseTime")
                        .HasColumnType("int")
                        .HasColumnName("Use_time");

                    b.Property<string>("VesselName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Vessel_name");

                    b.Property<string>("VoyageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Voyage_name");

                    b.Property<string>("Ycompany")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Ycompany");

                    b.Property<int?>("YunLock")
                        .HasColumnType("int")
                        .HasColumnName("YunLock");

                    b.HasKey("JobId");

                    b.HasIndex("Agent");

                    b.HasIndex("Carrier");

                    b.ToTable("tbl_JOB");
                });

            modelBuilder.Entity("PND_WEB.Models.TblShipper", b =>
                {
                    b.Property<string>("Shipper")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Shipper");

                    b.Property<string>("Saddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("SAddress");

                    b.Property<string>("Scity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SCity");

                    b.Property<string>("SpersonInCharge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SPerson_in_charge");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TaxID");

                    b.HasKey("Shipper");

                    b.ToTable("tbl_SHIPPER");
                });

            modelBuilder.Entity("PND_WEB.Models.TblSupplier", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Supplier_ID");

                    b.Property<string>("AddressSup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Address_sup");

                    b.Property<string>("LccFee")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LCC_Fee");

                    b.Property<string>("NameSup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name_sup");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Note");

                    b.Property<string>("Typer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Typer");

                    b.HasKey("SupplierId");

                    b.ToTable("tbl_SUPPLIER");
                });

            modelBuilder.Entity("PND_WEB.Models.TblSupplierAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note");

                    b.Property<string>("PersonInCharge")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Person_in_charge");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Phone_number");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Supplier_ID");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("tbl_SUPPLIER_ACTION");
                });

            modelBuilder.Entity("PND_WEB.Models.TblTutt", b =>
                {
                    b.Property<string>("SoTutt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SoTUTT");

                    b.Property<bool?>("Ceo")
                        .HasColumnType("bit")
                        .HasColumnName("ceo");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ghi_chu");

                    b.Property<bool?>("Ketoan")
                        .HasColumnType("bit")
                        .HasColumnName("ketoan");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime2")
                        .HasColumnName("Ngay");

                    b.Property<string>("NhanvienTutt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NhanvienTUTT");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Noi_dung");

                    b.Property<bool?>("xacnhanduyet")
                        .HasColumnType("bit")
                        .HasColumnName("xacnhanduyet");

                    b.HasKey("SoTutt");

                    b.ToTable("tbl_TUTT");
                });

            modelBuilder.Entity("PND_WEB.Models.Unit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CODE");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Note");

                    b.Property<string>("UnitName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Unit_name");

                    b.HasKey("Code");

                    b.ToTable("UNIT");
                });

            modelBuilder.Entity("TblTuttPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NghiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("SoHoaDon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoHoaDon");

                    b.Property<double?>("SoTien")
                        .HasColumnType("float")
                        .HasColumnName("SoTien");

                    b.Property<string>("SoTutt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SoTUTT");

                    b.Property<string>("TenPhi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenPhi");

                    b.Property<bool?>("Tt")
                        .HasColumnType("bit")
                        .HasColumnName("TT");

                    b.Property<bool?>("Tu")
                        .HasColumnType("bit")
                        .HasColumnName("TU");

                    b.HasKey("Id");

                    b.HasIndex("SoTutt");

                    b.ToTable("TblTuttsPhi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PND_WEB.Models.AppUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PND_WEB.Models.AppUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PND_WEB.Models.AppUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PND_WEB.Models.AppUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PND_WEB.Models.AgentAction", b =>
                {
                    b.HasOne("PND_WEB.Models.Agent", "CodeNavigation")
                        .WithMany("AgentActions")
                        .HasForeignKey("Code");

                    b.Navigation("CodeNavigation");
                });

            modelBuilder.Entity("PND_WEB.Models.CarrierAction", b =>
                {
                    b.HasOne("PND_WEB.Models.Carrier", "CodeNavigation")
                        .WithMany("CarrierActions")
                        .HasForeignKey("Code");

                    b.Navigation("CodeNavigation");
                });

            modelBuilder.Entity("PND_WEB.Models.QuotationsCharge", b =>
                {
                    b.HasOne("PND_WEB.Models.Quotation", "Quotation")
                        .WithMany("QuotationsCharges")
                        .HasForeignKey("QuotationId");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCharge", b =>
                {
                    b.HasOne("PND_WEB.Models.TblInvoice", "Debit")
                        .WithMany("TblCharges")
                        .HasForeignKey("DebitId");

                    b.Navigation("Debit");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCneeAdd", b =>
                {
                    b.HasOne("PND_WEB.Models.TblCnee", "CneeNavigation")
                        .WithMany("TblCneeAdds")
                        .HasForeignKey("Cnee");

                    b.Navigation("CneeNavigation");
                });

            modelBuilder.Entity("PND_WEB.Models.TblConth", b =>
                {
                    b.HasOne("PND_WEB.Models.TblHbl", "HblNavigation")
                        .WithMany("TblConths")
                        .HasForeignKey("HblNavigationHbl");

                    b.Navigation("HblNavigation");
                });

            modelBuilder.Entity("PND_WEB.Models.TblHbl", b =>
                {
                    b.HasOne("PND_WEB.Models.TblCnee", "CneeNavigation")
                        .WithMany("TblHbls")
                        .HasForeignKey("Cnee");

                    b.HasOne("PND_WEB.Models.TblCustomer", "Customer")
                        .WithMany("TblHbls")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PND_WEB.Models.TblJob", "Request")
                        .WithMany("TblHbls")
                        .HasForeignKey("RequestId");

                    b.HasOne("PND_WEB.Models.TblShipper", "ShipperNavigation")
                        .WithMany("TblHbls")
                        .HasForeignKey("Shipper");

                    b.Navigation("CneeNavigation");

                    b.Navigation("Customer");

                    b.Navigation("Request");

                    b.Navigation("ShipperNavigation");
                });

            modelBuilder.Entity("PND_WEB.Models.TblInvoice", b =>
                {
                    b.HasOne("PND_WEB.Models.TblHbl", "HblNavigation")
                        .WithMany("TblInvoices")
                        .HasForeignKey("HblNavigationHbl");

                    b.HasOne("PND_WEB.Models.TblSupplier", "Supplier")
                        .WithMany("TblInvoices")
                        .HasForeignKey("SupplierId");

                    b.Navigation("HblNavigation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PND_WEB.Models.TblJob", b =>
                {
                    b.HasOne("PND_WEB.Models.Agent", "AgentNavigation")
                        .WithMany("TblJobs")
                        .HasForeignKey("Agent");

                    b.HasOne("PND_WEB.Models.Carrier", "CarrierNavigation")
                        .WithMany("TblJobs")
                        .HasForeignKey("Carrier");

                    b.Navigation("AgentNavigation");

                    b.Navigation("CarrierNavigation");
                });

            modelBuilder.Entity("PND_WEB.Models.TblSupplierAction", b =>
                {
                    b.HasOne("PND_WEB.Models.TblSupplier", "Supplier")
                        .WithMany("TblSupplierActions")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TblTuttPhi", b =>
                {
                    b.HasOne("PND_WEB.Models.TblTutt", "SoTuttNavigation")
                        .WithMany("TblTuttPhis")
                        .HasForeignKey("SoTutt");

                    b.Navigation("SoTuttNavigation");
                });

            modelBuilder.Entity("PND_WEB.Models.Agent", b =>
                {
                    b.Navigation("AgentActions");

                    b.Navigation("TblJobs");
                });

            modelBuilder.Entity("PND_WEB.Models.Carrier", b =>
                {
                    b.Navigation("CarrierActions");

                    b.Navigation("TblJobs");
                });

            modelBuilder.Entity("PND_WEB.Models.Quotation", b =>
                {
                    b.Navigation("QuotationsCharges");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCnee", b =>
                {
                    b.Navigation("TblCneeAdds");

                    b.Navigation("TblHbls");
                });

            modelBuilder.Entity("PND_WEB.Models.TblCustomer", b =>
                {
                    b.Navigation("TblHbls");
                });

            modelBuilder.Entity("PND_WEB.Models.TblHbl", b =>
                {
                    b.Navigation("TblConths");

                    b.Navigation("TblInvoices");
                });

            modelBuilder.Entity("PND_WEB.Models.TblInvoice", b =>
                {
                    b.Navigation("TblCharges");
                });

            modelBuilder.Entity("PND_WEB.Models.TblJob", b =>
                {
                    b.Navigation("TblHbls");
                });

            modelBuilder.Entity("PND_WEB.Models.TblShipper", b =>
                {
                    b.Navigation("TblHbls");
                });

            modelBuilder.Entity("PND_WEB.Models.TblSupplier", b =>
                {
                    b.Navigation("TblInvoices");

                    b.Navigation("TblSupplierActions");
                });

            modelBuilder.Entity("PND_WEB.Models.TblTutt", b =>
                {
                    b.Navigation("TblTuttPhis");
                });
#pragma warning restore 612, 618
        }
    }
}
